User.create(username:              "example",
            email:                 "example@me.com",
            password:              "password",
            password_confirmation: "password",
            height_feet:           6,
            height_inches:         2,
            weight:                180,
            max_bench:             200,
            max_squat:             300,
            max_deadlift:          400,
            level:                "Intermediate",
            goal:                  "Lose Weight",
            )

lifts = [{name: "Bench Press", upper_lower: "Upper", primary_muscle: "Chest", secondary_muscle: "Triceps", push_pull: "Push", instructions_one: "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.", instructions_two: "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.", instructions_three: "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.", instructions_four: "Repeat the movement for the prescribed amount of repetitions.", instructions_five: "When you are done, place the bar back in the rack."},
         {name: "Dumbbell Curls", upper_lower: "Upper", primary_muscle: "Biceps", secondary_muscle: "Forearms", push_pull: "Pull", instructions_one: "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.", instructions_two: "Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.", instructions_three: "Then, inhale and slowly begin to lower the dumbbells back to the starting position.", instructions_four: "Repeat for the recommended amount of repetitions."},
         {name: "Tricep Pushdown", upper_lower: "Upper", primary_muscle: "Triceps", push_pull: "Push", instructions_one: "Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.", instructions_two: "Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.", instructions_three: "Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.", instructions_four: "After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.", instructions_five: "Repeat for the recommended amount of repetitions."},
         {name: "Barbell Squat", upper_lower: "Lower", primary_muscle: "Quadriceps", secondary_muscle: "Glutes", push_pull: "Push", instructions_one: "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.", instructions_two: "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.", instructions_three: "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position.", instructions_four: "Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement.", instructions_five: "Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.", instructions_six: "Repeat for the recommended amount of repetitions."},
         {name: "Standing Military Press", upper_lower: "Upper", primary_muscle: "Shoulders", secondary_muscle: "Triceps", push_pull: "Push", instructions_one: "Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.", instructions_two: "Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.", instructions_three: "Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.", instructions_four: "Lower the bar down to the collarbone slowly as you inhale.", instructions_five: "Lift the bar back up to the starting position as you exhale.". instructions_six: "Repeat for the recommended amount of repetitions."},
         {name: "Pullups", upper_lower: "Upper", primary_muscle: "Lats", secondary_muscle: "Biceps", push_pull: "Pull", instructions_one: "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.", instructions_two: "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.", instructions_three: "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.", instructions_four: "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.", instructions_five: "Repeat this motion for the prescribed amount of repetitions."}
        ]

lifts.each do |lift|
  Lift.create(name: lift[:name],
              upper_lower: lift[:upper_lower],
              primary_muscle: lift[:primary_muscle],
              secondary_muscle: lift[:secondary_muscle],
              push_pull: lift[:push_pull],
              instructions_one: lift[:instructions_one],
              instructions_two: lift[:instructions_two],
              instructions_three: lift[:instructions_three],
              instructions_four: lift[:instructions_four],
              instructions_five: lift[:instructions_five],
              instructions_six: lift[:instructions_six],
              instructions_seven: lift[:instructions_seven],
              )
end